name: Sía töflu
run-name: 
on: 
  push:
    paths:
      - 'ordaskra_table.tex'
jobs:
  sia_toflu:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hef meðhöndlun á 'ordaskra_table.tex'"
      - name: Checkout repo
        uses: actions/checkout@v7.0.0
      - run: python process_table.py
      - run: echo "Meðhöndlun tókst, niðurstaðan hefur verið vistuð í 'ordaskra_table_finished.tex'
